[package]
name = "math_format_macro"
version = "0.1.0"
publish = false

[lib]
proc-macro = true

[dependencies]
itertools = "0.10.3"
phf = { version = "0.10", features = ["macros"] }
proc-macro2 = "1.0.36"
quote = "1.0"
syn = { version = "1.0.89", features = ["full"] }
