[package]
name = "polykit"
version = "0.1.0"
authors = ["Andrei Matveiakin <a.matveiakin@gmail.com>"]
edition = "2021"

[dependencies]
num = "0.4"
smallvec = { version = "1.8.0", features = ["union", "const_generics", "const_new"] }
trait-set = "0.3.0"
tuple-conv = "1.0.1"
