cc_binary(
    name = "shuffle_unroll",
    srcs = ["shuffle_unroll.cpp"],
    deps = ["//:math"],
)

cc_binary(
    name = "shuffle_unroll_multi",
    srcs = ["shuffle_unroll_multi.cpp"],
    deps = ["//:math"],
)
