name: C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v3
    - name: apt install
      run: sudo apt-get install -y libtbb-dev liblinbox-dev libgmp-dev libntl-dev
    - name: test
      run: cd cpp && ./test_everything.sh
